### ISSUE TITLE
[BUG] can't load julia-client package

### ISSUE THREAD

**Issue by EdHarry** [JunoLab/Juno.jl#327]
[Enter steps to reproduce:]

1. brew cask install atom
2. apm install julia-client
3. start atom

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.8.10

### Stack Trace

Failed to load the julia-client package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at Object.home (/packages/julia-client/lib/misc/paths.coffee:9:5)
    at /packages/julia-client/lib/misc/history.coffee:7:15)
    at /packages/julia-client/lib/misc/history.coffee:1:1)
    at /packages/julia-client/lib/misc/history.coffee:1:1)
    at Module.get_Module._compile (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/julia-client/lib/misc.coffee:5:12)
    at /packages/julia-client/lib/misc.coffee:1:1)
    at /packages/julia-client/lib/misc.coffee:1:1)
    at Module.get_Module._compile (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/julia-client/lib/connection.coffee:1:10)
    at /packages/julia-client/lib/connection.coffee:1:1)
    at /packages/julia-client/lib/connection.coffee:1:1)
    at Module.get_Module._compile (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/julia-client/lib/package/config.coffee:1:14)
    at /packages/julia-client/lib/package/config.coffee:1:1)
    at /packages/julia-client/lib/package/config.coffee:1:1)
    at Module.get_Module._compile (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/julia-client/lib/julia-client.coffee:4:10)
    at /packages/julia-client/lib/julia-client.coffee:1:1)
    at /packages/julia-client/lib/julia-client.coffee:1:1)
    at Module.get_Module._compile (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:686763)
    at Package.requireMainModule (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3430498)
    at measure (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3417209)
    at Package.measure (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3416041)
    at Package.load (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3416782)
    at PackageManager.loadAvailablePackage (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379754)
    at config.transact (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:378177)
    at Config.transact (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:330642)
    at PackageManager.loadPackages (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:378115)
    at t.loadState.then (/Users/eh15/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:707261)
    at <anonymous>
```

### Commands

```
     -3:05.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
indent-detective 0.3.3 
ink 0.10.11 
julia-client 0.8.10 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Probably fixed by now. Please reopen if that's not the case.
