### ISSUE TITLE
Error: Installing “julia-client@0.9.4” failed.

### ISSUE THREAD

**Issue by helenzhangtianyue** [JunoLab/Juno.jl#341]
Error: Installing “julia-client@0.9.4” failed.
Installing julia-client to /Users/helennnnnnnn/.atom/packages ✗

> @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install /private/var/folders/hb/kw66dgw52plc69nx6nlskn9c0000gn/T/apm-install-dir-119713-4770-12mju58.3qkr/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/hb/kw66dgw52plc69nx6nlskn9c0000gn/T/apm-install-dir-119713-4770-12mju58.3qkr/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/hb/kw66dgw52plc69nx6nlskn9c0000gn/T/apm-install-dir-119713-4770-12mju58.3qkr/package.json'
npm WARN apm-install-dir-119713-4770-12mju58.3qkr No description
npm WARN apm-install-dir-119713-4770-12mju58.3qkr No repository field.
npm WARN apm-install-dir-119713-4770-12mju58.3qkr No README data
npm WARN apm-install-dir-119713-4770-12mju58.3qkr No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Details
- Atom version:1.40.0
- Julia version:1.1.1
- OS: OS X 10.14.6
- Package versions:
  - Atom.jl:
  - julia-client:julia-client@0.9.4
  - ink:0.10.12
 -uber-juno: 0.2.0

apm -v:
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.6.3
git 2.15.0

I am using a mac, and pretty sure my internet connection is fine. I'm not sure how to solve this, could someone please help me out?

**Comment by helenzhangtianyue** [comment]
Fixed by downloading python 2.7.16 and run
npm config set python /usr/bin/python2.7
