### ISSUE TITLE
Julia-client bugs everytime it is updated

### ISSUE THREAD

**Issue by HenriDeh** [JunoLab/Juno.jl#344]
Everytime the julia-client is updated there's that same annoying bug. The toolbar on the side disappears, the REPL is named "terminal" and doesn't run a julia process, the julia-client package in atom's list of installed packages does not have a "settings" button. The way I used to work around that was uninstall reinstall the package until it worked. Now I can't even uninstall it, it just doesn't react when I click uninstall. If I disable it before uninstalling an error window pops (in atom) saying:

```
Uncaught TypeError: this.pack.activateConfig is not a function

C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\static\<embedded>:14
Show Stack Trace
This is likely a bug in Atom. This issue has already been reported.
```
and there's a link to [this issue](https://github.com/atom/atom/issues/16270)

julia-client version : not specified in atom, I assume it's 0.9.4 since it was updated. 
atom version : 1.40.0

**Comment by HenriDeh** [comment]
I manually deleted the package by deleting the folder in .atom/packages. Now there is an error when I trying to install julia-client : 

```
nstalling “julia-client@0.9.4” failed.Hide output…

> @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119716-2872-pof98j.f3x7\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119716-2872-pof98j.f3x7\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\Henri\AppData\Local\Programs\Python\Python37-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Henri\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Henri\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119716-2872-pof98j.f3x7\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119716-2872-pof98j.f3x7\package.json'
npm WARN apm-install-dir-119716-2872-pof98j.f3x7 No description
npm WARN apm-install-dir-119716-2872-pof98j.f3x7 No repository field.
npm WARN apm-install-dir-119716-2872-pof98j.f3x7 No README data
npm WARN apm-install-dir-119716-2872-pof98j.f3x7 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Henri\.atom\.apm\_logs\2019-08-16T15_46_09_026Z-debug.log
```

**Comment by HenriDeh** [comment]
Reverting to Atom 1.39.0 fixed the issue. I'll disable automatic Atom updates from now on.

**Comment by aviatesk** [comment]
Sorry for the confuses around the recent updates.
The issue you're facing is exactly same as the one reported [here](https://discourse.julialang.org/t/juno-fails-to-install-julia-client-0-9-4/27544/2) so please watch it for updates.
