### ISSUE TITLE
Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by bgodard** [JunoLab/Juno.jl#352]
Fresh atom 1.40.1 install from github Linux 64 bits official binary on OS Oracle Linux Enterprise 7.6.

After installing juno, I get the message:
```
Failed to load the julia-client package
Cannot find module '../build/Debug/pty.node'
```
Atom says this issue has already been reported here:
https://github.com/JunoLab/atom-julia-client/issues/591

but I think this is a different issue (different error message and this issue is marked as fix for Atom 1.40.1).

Remarks:
- With the OS, I did not have this problem with my previous install ( a few months ago) of Atom/Juno.
- On my Ubuntu 18.04 64bits with Atom 1.40.1 (from flatpak/flathub package), I also do not have this problem.
- Probably unrelated, but I just migrated to Julia 1.2 from 1.1 on both systems.

Stack trace:
```
Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:155413)
    at Module.require (file:///local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app.asar/static/index.js:61:43)
    at require (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:146745)
    at Object.loadNative (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/utils.js:22:16)
    at Object.<anonymous> (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:24:19)
    at Object.<anonymous> (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:255:3)
    at Module.get_Module._compile (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app.asar/static/index.js:72:46)
    at require (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:14:20)
    at Object.<anonymous> (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:52:3)
    at Module.get_Module._compile (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app.asar/static/index.js:72:46)
    at require (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/lib/connection/process/basic2.js:3:24)
    at Object.<anonymous> (/local/scratch/bgodard/sw/atom-user-config/packages/julia-client/lib/connection/process/basic2.js:174:2)
    at Module.get_Module._compile (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/local/scratch/bgodard/sw/atom-1.40.1-amd64/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
```

**Comment by leifdenby** [comment]
I have the same issue with fresh atom 1.40.1 install on CentOS Linux 7

**Comment by bgodard** [comment]
Same problem with 1.39.1
Works with 1.38.2, but is not really functional:
- after a few sessions, I get 
```
┌ Warning: Terminal not fully functional
└ @ Base client.jl:381
```
when starting the julia console and the variables from the console session do not appear in the workspace anymore.
- the default panes are not opened at startup even though I chose to enable this when installing julia client.

This is with julia 1.2, but switching back to 1.1.1 leads to same results.

I used to have it working in 1.37 but last week I started getting this "Terminal not fully functional" error. This is when I decided to upgrade to latest/1.40.1.

**Comment by pfitzseb** [comment]
Someone on slack fixed this with 
> sorted by upgrading libstdc++ from 6.0.19 to 6.0.26

There's a `try ... catch` in one of our dependencies that hides the original error, which was 
```
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /bmm/home/et517/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/build/Release/pty.node)
```
for him.

**Comment by bgodard** [comment]
@pfitzweb Thank you for your reply. I guess Enterprise Linux 7 is not supported anymore. Well that's the usual problem with Enterprise Linux distributions.

**Comment by bgodard** [comment]
I can confirm adding:
```cpp
export LD_PRELOAD=${JULIA_INSTALL}/lib/julia/libstdc++.so.6
```
to my atom startup script fixes the problem

**Comment by bgodard** [comment]
> I see the same issue on CentOS 7 with Atom 1.40.1
> At least on CentOS 7 the Julia binary does not seem to come with it's own C++ library.

I am using Julia official binaries for Linux not a distribution package.

**Comment by mrl00** [comment]
> > I see the same issue on CentOS 7 with Atom 1.40.1
> > At least on CentOS 7 the Julia binary does not seem to come with it's own C++ library.
> 
> I am using Julia official binaries for Linux not a distribution package.

hot to fix it using distribution package?

**Comment by pfitzseb** [comment]
I'd highly encourage using the official binaries -- no one except your distro maintainers can really give you any support otherwise.
