### ISSUE TITLE
[BUG] Juno Plots blurry on HiDPI displays

### ISSUE THREAD

**Issue by milesfrain** [JunoLab/Juno.jl#353]
Plots are blurry in the Juno plot pane on a 4K HiDPI monitor with 200% scaling. See the first plot in the image below.

This is not an issue when launching plots from a terminal instance of Julia (see second plot).

The third plot takes the 200% scaling factor into account, which makes it more readable. Not sure if dpi settings could (or should) be automatically detected and then applied to plots. I'd be happy if Juno could produce output equivalent to the crispness of the second plot, since users could then further customize for their desired scaling.

![juno-plot-hidpi](https://user-images.githubusercontent.com/3578681/64494215-10e92c00-d23f-11e9-83b4-3f87ddb848e2.png)

### Versions
- Atom version: 1.34
- Julia version: 1.2.0
- OS: Ubuntu 18.04
- Package versions:
  - Atom.jl: 0.10.1
  - julia-client: ?
  - ink: ?

**Comment by milesfrain** [comment]
Simplest workaround for now is to disable the Juno plot pane:
```
Julia > Settings... > uncheck “Enable Plot Pane”
```

**Comment by milesfrain** [comment]
Might be related to a [similar issue in JupyterLab](https://github.com/altair-viz/altair/issues/1002)

**Comment by pfitzseb** [comment]
The plot pane size doesn't take the `devicePixelRatio` into account, so this totally makes sense. Should be easy enough to fix though.

**Comment by pfitzseb** [comment]
Can you test https://github.com/JunoLab/atom-julia-client/pull/609 by cloning that repo, `cd`'ing into it, and then calling
```
git checkout sp/dpiplots
apm install
apm link -d
```
after which you can start Atom with `atom -d` to get the new behaviour?

**Comment by milesfrain** [comment]
Thanks for the impressively fast turnaround time on this.

Encountered the below error.
As a sanity check, I switched to the master branch, repeated the same install steps, and got the identical error.

Wondering if this is a version mismatch.

Here are my versions:
Atom 1.40.1
julia-client 0.10.1
language-julia 0.19.1
ink 0.11.0
uber-juno 0.2.0

```
Cannot find module '../build/Debug/pty.node'
Hide Stack Trace
Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:336:28)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:68:27)
    at Object.loadNative (/home/miles/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/utils.js:22:16)
    at Object.<anonymous> (/home/miles/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:24:19)
    at Object.<anonymous> (/home/miles/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:255:3)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/miles/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:14:20)
    at Object.<anonymous> (/home/miles/.atom/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:52:3)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/miles/temp/atom-julia-client/lib/connection/process/basic2.js:3:24)
    at Object.<anonymous> (/home/miles/temp/atom-julia-client/lib/connection/process/basic2.js:174:2)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by milesfrain** [comment]
I can play around with some of these settings and report back if you have any suggestions of other knobs to turn. Was looking at `webview` `style` too.
Is it possible to change the .js code while Juno is running? Or at least trigger a package refresh? My debug cycle now involves restarting Juno and Julia (and waiting for first plot) between every change.

Also would be good to split the decaffeinate change and DPI change into two separate commits to make it more obvious what's being modified. I believe the DPI adjustment just involves `.map(x => x*window.devicePixelRatio)`

**Comment by pfitzseb** [comment]
Alright, so the right way forward seems to be to multiply the reported plot size by `devicePixelRation` and then scale the displayed plot by `1/devicePixelRatio`? I'll ask the plots people if there's a better way to handle this though.

>  Is it possible to change the .js code while Juno is running? Or at least trigger a package refresh? My debug cycle now involves restarting Juno and Julia (and waiting for first plot) between every change.

No, that's the only way, unfortunately.

> Also would be good to split the decaffeinate change and DPI change into two separate commits to make it more obvious what's being modified. I believe the DPI adjustment just involves .map(x => x*window.devicePixelRatio)

Good call, done.

**Comment by pfitzseb** [comment]
Ok, https://github.com/JuliaPlots/Plots.jl/pull/2190 and linked PRs should fix this issue. Can you try this fix (I realize it's a bunch of packages to check out)?

**Comment by milesfrain** [comment]
Not quite there yet.

Currently miscalculates the available horizontal an vertical spacing and assumes 2x space is available.

#### Restrict width
![image](https://user-images.githubusercontent.com/3578681/65215251-c6975480-da61-11e9-93cd-5316a866f146.png)

#### Restrict height
![image](https://user-images.githubusercontent.com/3578681/65215290-ed558b00-da61-11e9-9ae2-b23fd70d629b.png)

**Comment by daschw** [comment]
Maybe the `jdpi` factor also needs to go into the `scale` factor in https://github.com/JuliaPlots/Plots.jl/blob/2c3bffaf766a6ca9eaf0a3fd446e89269d0e9503/src/output.jl#L234-L255

Could you test this @milesfrain and submit a PR to Plots if it works or report back?

**Comment by pfitzseb** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/2196 might or might not do the trick.

**Comment by milesfrain** [comment]
Here's what JuliaPlots/Plots.jl#2196 produces:
![image](https://user-images.githubusercontent.com/3578681/65276455-9b9e1680-dadc-11e9-85be-5e19222330f0.png)
Sized correctly, and scaled to match system fonts, but still blurry.
Added some [debug prints](https://github.com/milesfrain/Plots.jl/commit/d3e4032264c5b66c58873e2e8cec119ecac61fb1), and full logs of that are at the end of this message.

Fixing blurriness requires a change in atom-ink. There might be other ways to achieve this same desired effect, but I suspect this change needs to happen in ink.

The below screenshots were generated with these two changes applied.
https://github.com/JunoLab/atom-ink/pull/226
https://github.com/JuliaPlots/Plots.jl/pull/2199

### What plots look like now.
This most closely matches external plot window output. (see original message in this thread).
![image](https://user-images.githubusercontent.com/3578681/65273838-e4eb6780-dad6-11e9-9486-cb40629c6966.png)

### Increased plot size to match system scaling factor
This seems to be a more proportional scaling to match the rest of the system, but could make some elements comically large. This should be an additional option or FAQ topic, rather than the default.
```
s=2; plot(sin, dpi=default(:dpi)*s, size=default(:size)./s)
```
![image](https://user-images.githubusercontent.com/3578681/65273910-1401d900-dad7-11e9-9cb5-31ade44ad208.png)

### Another scaling factor adjustment
I think `s=1.5` is the most balanced. So more reason to let this be up to user-preference.
```
s=1.5; plot(sin, dpi=default(:dpi)*s, size=default(:size)./s)
```
![image](https://user-images.githubusercontent.com/3578681/65274811-0c433400-dad9-11e9-92c6-23882e05ec85.png)

Here are the complete debug printouts of the different scaling factors. I couldn't get breakpoints to work in `output.jl` btw. Also interesting that `showjuno()` is called 4 times per plot.
```
julia> plot(sin)
 -------------------- 
sz [600, 400]
dpi 100
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 0.7516666666666667
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 0.7516666666666667
 -------------------- 
sz [451.0, 300.6666666666667]
dpi 200
thickness_scaling 0.7516666666666667
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.0
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 0.7516666666666667
f size [451.0, 300.6666666666667]
f dpi 200
f thickness_scaling 0.7516666666666667
f size [600, 400]
f dpi 100
f thickness_scaling 1
 -------------------- 
sz [600, 400]
dpi 100
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 0.7516666666666667
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 0.7516666666666667
f size [600, 400]
f dpi 100
f thickness_scaling 1
 -------------------- 
sz [600, 400]
dpi 100
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 0.7516666666666667
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 0.7516666666666667
f size [600, 400]
f dpi 100
f thickness_scaling 1

julia> s=2; plot(sin, dpi=default(:dpi)*s, size=default(:size)./s)
 -------------------- 
sz [300.0, 200.0]
dpi 200
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.5033333333333334
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.5033333333333334
 -------------------- 
sz [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.5033333333333334
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.0
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.5033333333333334
f size [451.0, 300.6666666666667]
f dpi 200
f thickness_scaling 1.5033333333333334
f size [300.0, 200.0]
f dpi 200
f thickness_scaling 1
 -------------------- 
sz [300.0, 200.0]
dpi 200
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.5033333333333334
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.5033333333333334
f size [300.0, 200.0]
f dpi 200
f thickness_scaling 1
 -------------------- 
sz [300.0, 200.0]
dpi 200
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.5033333333333334
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.5033333333333334
f size [300.0, 200.0]
f dpi 200
f thickness_scaling 1

julia> s=1.5; plot(sin, dpi=default(:dpi)*s, size=default(:size)./s)
 -------------------- 
sz [400.0, 266.6666666666667]
dpi 150.0
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.1275
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.1275
 -------------------- 
sz [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.1275
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.0
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.1275
f size [451.0, 300.6666666666667]
f dpi 200
f thickness_scaling 1.1275
f size [400.0, 266.6666666666667]
f dpi 150.0
f thickness_scaling 1
 -------------------- 
sz [400.0, 266.6666666666667]
dpi 150.0
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.1275
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.1275
f size [400.0, 266.6666666666667]
f dpi 150.0
f thickness_scaling 1
 -------------------- 
sz [400.0, 266.6666666666667]
dpi 150.0
thickness_scaling 1
jsize Any[451, 368]
jratio 2
Plots.DPI 100
scale 1.1275
size [451.0, 300.6666666666667]
dpi 200
thickness_scaling 1.1275
f size [400.0, 266.6666666666667]
f dpi 150.0
f thickness_scaling 1
```

Logs of the original JuliaPlots/Plots.jl#2196
```
julia> plot(sin)
 -------------------- 
sz [600, 400]
dpi 100
thickness_scaling 1
jsize Any[451, 366]
jratio 2
Plots.DPI 100
scale 0.7516666666666667
size [225.5, 150.33333333333334]
dpi 200
thickness_scaling 0.7516666666666667
 -------------------- 
sz [225.5, 150.33333333333334]
dpi 200
thickness_scaling 0.7516666666666667
jsize Any[451, 366]
jratio 2
Plots.DPI 100
scale 2.0
size [225.5, 150.33333333333334]
dpi 200
thickness_scaling 1.5033333333333334
f size [225.5, 150.33333333333334]
f dpi 200
f thickness_scaling 0.7516666666666667
f size [600, 400]
f dpi 100
f thickness_scaling 1
 -------------------- 
sz [600, 400]
dpi 100
thickness_scaling 1
jsize Any[451, 366]
jratio 2
Plots.DPI 100
scale 0.7516666666666667
size [225.5, 150.33333333333334]
dpi 200
thickness_scaling 0.7516666666666667
f size [600, 400]
f dpi 100
f thickness_scaling 1
 -------------------- 
sz [600, 400]
dpi 100
thickness_scaling 1
jsize Any[451, 366]
jratio 2
Plots.DPI 100
scale 0.7516666666666667
size [225.5, 150.33333333333334]
dpi 200
thickness_scaling 0.7516666666666667
f size [600, 400]
f dpi 100
f thickness_scaling 1
```
