### ISSUE TITLE
[BUG] Unable to update julia-client along with the new juno update

### ISSUE THREAD

**Issue by HenriDeh** [JunoLab/Juno.jl#397]
## Details
- Atom version: 1.40.x
- Julia version: 1.1
- OS: Win 10
- Package versions:
  - Atom.jl: 0.11.1
  - julia-client: uninstalled
  - ink: 0.11.5
  - uber-juno: 0.3

When installing uber-juno, julia-client is not installed as a dependency as it used to be. Installing julia-client manually returns:

````
Packages are published to atom.io and are installed to C:\Users\Henri\.atom\packages
Installing “julia-client@0.11.2” failed.Hide output…

> @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119915-15496-lv11jl.7eb6\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119915-15496-lv11jl.7eb6\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\Henri\AppData\Local\Programs\Python\Python37-32\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Henri\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Henri\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Henri\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119915-15496-lv11jl.7eb6\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Henri\AppData\Local\Temp\apm-install-dir-119915-15496-lv11jl.7eb6\package.json'
npm WARN apm-install-dir-119915-15496-lv11jl.7eb6 No description
npm WARN apm-install-dir-119915-15496-lv11jl.7eb6 No repository field.
npm WARN apm-install-dir-119915-15496-lv11jl.7eb6 No README data
npm WARN apm-install-dir-119915-15496-lv11jl.7eb6 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Henri\.atom\.apm\_logs\2019-10-15T11_13_46_358Z-debug.log


```

**Comment by pfitzseb** [comment]
Atom 1.40.0 has a bug that prevents the installation of julia-client. Please update to 1.40.1 and try again.

**Comment by HenriDeh** [comment]
Thank you this worked
