### ISSUE TITLE
[BUG] Juno freezes during single line execution via "shift + enter"

### ISSUE THREAD

**Issue by VoSiLk** [JunoLab/Juno.jl#405]
## Details
- Atom version 1.40.1
- Julia version: 1.2.0
- OS: Windows 10
- Package versions:
  - Atom.jl: v0.11.2
  - julia-client:0.11.2
  - ink: 0.11.5

### Steps to reproduce
Sometimes when I try to load packages i.e. 

```julia 
using JLD2
using Plots
plotly()
using DataFrames
using CSV
using Flux
```
and hold shift + enter for some seconds to execute some specific lines. Or when I use CSV.read. The same code in IJulia doesn´t make this problem.

**Comment by VoSiLk** [comment]
The weird thing is: When I copy the code to the REPL the code will be evaluated. And after I executed the code in the REPL and then use shift + enter Juno also gives a positive check mark.

**Comment by pfitzseb** [comment]
Are you sure the code isn't just taking a while to execute?

**Comment by VoSiLk** [comment]
Yes I´m sure. I waited several minutes (approx. 5 min) and the evaluation time in the REPL and in IJulia takes just a few seconds. Also the "run all" doesn´t work for me correctly anymore. I have reinstalled Atom and Juno and the Julia packages for Atom and Juno, but it doesn´t solve the problem. Only when I run a script with include in the REPL the code will be executed.

**Comment by pfitzseb** [comment]
Can you paste the Juno debug info here (which you can get with the `Julia Client: Debug Info` command or the `Juno > Debug Information`  menu entry)?

**Comment by VoSiLk** [comment]
# Atom:
Version: 1.41.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.11.2
Config:
{
  "firstBoot": false,
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}


# ink:
Version: 0.11.5
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.1
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:
Version: 0.3.6
Config:
undefined


Could not connect to Julia.

**Comment by pfitzseb** [comment]
> Could not connect to Julia.

Ok, so Julia isn't even properly starting up (or at least we can't communicate with it). Are there any error messages in the integrated REPL? If not, please open the dev tools with <kbd>Ctrl-Shift-I</kbd> and look in the console there.

**Comment by VoSiLk** [comment]
spell-check:en-us The package `spell-check` cannot load the system dictionary for `en_US`. See the settings for ways of changing the languages used,  resolving missing dictionaries, or hiding this warning.

The plugin checked the following paths for dictionary files:
* C:\
* C:\Users\VoSiLk\AppData\Local\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 1.51s
19internal/process/next_tick.js:68 Uncaught (in promise) disconnected
internal/modules/cjs/loader.js:584 Uncaught (in promise) Error: Cannot find module 'log4js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\VoSiLk\AppData\Local\atom\app-1.41.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\VoSiLk\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/VoSiLk/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\VoSiLk\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:163921)
    at t (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:270)
    at a (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:155427)
    at C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:159986
    at Generator.throw (<anonymous>)
    at r (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:139599)
    at s (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:139720)
    at process._tickCallback (internal/process/next_tick.js:68:7)
4C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1 Uncaught (in promise) TypeError: (0 , (y || a(...)).getLogger) is not a function
    at C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:160001
    at Generator.throw (<anonymous>)
    at r (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:139599)
    at s (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:139720)
    at process._tickCallback (internal/process/next_tick.js:68:7)
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 1.06s
6C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
8internal/process/next_tick.js:68 Uncaught (in promise) disconnected
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 0.84s
6C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
events.js:167 Uncaught Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:78)
    at writeGeneric (internal/stream_base_commons.js:73)
    at Socket._writeGeneric (net.js:713)
    at Socket.connect (net.js:695)
    at Object.onceWrapper (events.js:273)
    at Socket.emit (events.js:182)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099)
3internal/process/next_tick.js:68 Uncaught (in promise) disconnected
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 0.84s
5C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 1.40s
C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
internal/process/next_tick.js:68 Uncaught (in promise) disconnected
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 1.42s
5C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
3internal/process/next_tick.js:68 Uncaught (in promise) disconnected
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 1.42s
3C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
16internal/process/next_tick.js:68 Uncaught (in promise) disconnected
10C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1 Uncaught (in promise) TypeError: (0 , (y || a(...)).getLogger) is not a function
    at C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:160001
    at Generator.throw (<anonymous>)
    at r (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:139599)
    at s (C:\Users\VoSiLk\.atom\packages\hyperclick\index.js:1:139720)
    at process._tickCallback (internal/process/next_tick.js:68:7)
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 1.11s
4C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117 Error: Something went wrong while evaluating.
(anonymous) @ C:\Users\VoSiLk\.atom\packages\julia-client\lib\runtime\evaluation.coffee:117
C:\Users\VoSiLk\.atom\packages\julia-client\lib\misc.coffee:45 Julia Boot: 0.09s

**Comment by pfitzseb** [comment]
Hm. Can you start Julia outside of Atom (e.g. with the `Julia Client: Open External REPL` command) and check `versioninfo()` and `pkg> status`?

**Comment by pfitzseb** [comment]
Ok, that looks correct. Does `using Atom` work fine?

**Comment by VoSiLk** [comment]
I think so. I typed the following in the REPL outside of Atom. I also tested the package with Pkg.test("Atom"). All tests passed, but there was also an error message ┌ Error: MethodError(Tokenize.Tokens.RawToken, (Tokenize.Tokens.EQEQ, (7, 12), (7, 14), 118, 119, Tokenize.Tokens.NO_ERR, false), 0x000000000000662c). I don´t know if it helps you. 

julia> using Atom

julia> using Pkg

julia> Pkg.test("Atom")
  Updating registry at `C:\Users\VoSiLk\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Testing Atom
 Resolving package versions...
 Installed Example ─ v0.5.3
    Status `C:\Users\VoSiLk\AppData\Local\Temp\jl_3ABfrq\Manifest.toml`
  [bf4720bc] AssetRegistry v0.1.0
  [c52e3926] Atom v0.11.2
  [b99e7846] BinaryProvider v0.5.6
  [00ebfdb7] CSTParser v0.6.2
  [7057c7e9] Cassette v0.2.6
  [53a63b46] CodeTools v0.6.4
  [da1fd8a2] CodeTracking v0.5.8
  [3da002f7] ColorTypes v0.8.0
  [5ae59095] Colors v0.9.6
  [34da2185] Compat v2.2.0
  [864edb3b] DataStructures v0.15.0
  [b4f34e82] Distances v0.8.2
  [33d173f1] DocSeeker v0.3.1
  [7876af07] Example v0.5.3
  [53c48c17] FixedPointNumbers v0.6.1
  [de31a74c] FunctionalCollections v0.5.0
  [cd3eb016] HTTP v0.8.6
  [9fb69e20] Hiccup v0.2.2
  [83e8ac13] IniFile v0.5.0
  [682c06a0] JSON v0.21.0
  [98e50ef6] JuliaFormatter v0.1.16
  [aa1ae85d] JuliaInterpreter v0.7.4
  [e5e0dc1b] Juno v0.7.2
  [7c4cb9fa] LNR v0.2.0
  [50d2b5c4] Lazy v0.13.2
  [1914dd2f] MacroTools v0.5.1
  [739be429] MbedTLS v0.7.0
  [e89f7d12] Media v0.5.0
  [510215fc] Observables v0.2.3
  [bac558e1] OrderedCollections v1.1.0
  [69de0a69] Parsers v0.3.7
  [fa939f87] Pidfile v1.1.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [88034a9c] StringDistances v0.4.0
  [0796e94c] Tokenize v0.5.6
  [37b6cedf] Traceur v0.3.0
  [a2a6695c] TreeViews v0.3.0
  [30578b45] URIParser v0.4.0
  [0f1e0344] WebIO v0.8.11
  [104b5d7c] WebSockets v1.5.2
  [cc8bc4a8] Widgets v0.6.2
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [7b1f6079] FileWatching  [`@stdlib/FileWatching`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
Test Summary:          | Pass  Total
basic message handling |    6      6
Test Summary:  | Pass  Total
path utilities |   21     21
Test Summary:     | Pass  Total
REPL path finding |    4      4
Test Summary:        | Pass  Total
finding dev packages |    1      1
Test Summary: | Pass  Total
get utilities |    4      4
Test Summary:              | Pass  Total
limiting excessive strings |    8      8
Test Summary: | Pass  Total
toggle docs   |    3      3
Test Summary:  | Pass  Total
local bindings |   61     61
Test Summary: | Pass  Total
outline       |   32     32
Test Summary: | Pass  Total
completions   |   26     26
Test Summary:     | Pass  Total
local completions |    4      4
┌ Info: Start regenerating symbols cache
└   progress = 0
┌ Info: Symbols: Dates (1 / 63)
└   progress = 0.015873015873015872
┌ Info: Symbols: Distances (2 / 63)
└   progress = 0.031746031746031744
┌ Info: Symbols: CodeTracking (3 / 63)
└   progress = 0.047619047619047616
┌ Info: Symbols: Lazy (4 / 63)
└   progress = 0.06349206349206349
┌ Info: Symbols: Media (5 / 63)
└   progress = 0.07936507936507936
┌ Info: Symbols: StringDistances (6 / 63)
└   progress = 0.09523809523809523
┌ Info: Symbols: URIParser (7 / 63)
└   progress = 0.1111111111111111
┌ Info: Symbols: LibGit2 (9 / 63)
└   progress = 0.14285714285714285
┌ Info: Symbols: CRC32c (10 / 63)
└   progress = 0.15873015873015872
┌ Info: Symbols: Profile (11 / 63)
└   progress = 0.1746031746031746
┌ Info: Symbols: Libdl (12 / 63)
└   progress = 0.19047619047619047
┌ Info: Symbols: Random (13 / 63)
└   progress = 0.20634920634920634
┌ Info: Symbols: Parsers (14 / 63)
└   progress = 0.2222222222222222
┌ Info: Symbols: JuliaFormatter (15 / 63)
└   progress = 0.23809523809523808
┌ Info: Symbols: CodeTools (16 / 63)
└   progress = 0.25396825396825395
┌ Info: Symbols: Base (17 / 63)
└   progress = 0.2698412698412698
┌ Info: Symbols: Future (18 / 63)
└   progress = 0.2857142857142857
┌ Info: Symbols: LNR (19 / 63)
└   progress = 0.30158730158730157
┌ Info: Symbols: Serialization (20 / 63)
└   progress = 0.31746031746031744
┌ Info: Symbols: Hiccup (21 / 63)
└   progress = 0.3333333333333333
┌ Info: Symbols: Atom (22 / 63)
└   progress = 0.3492063492063492
┌ Info: Symbols: CSTParser (23 / 63)
└   progress = 0.36507936507936506
┌ Info: Symbols: DelimitedFiles (24 / 63)
└   progress = 0.38095238095238093
┌ Info: Symbols: Compat (25 / 63)
└   progress = 0.3968253968253968
┌ Error: MethodError(Tokenize.Tokens.RawToken, (Tokenize.Tokens.STAR, (733, 16), (733, 17), 24836, 24836, Tokenize.Tokens.NO_ERR, false), 0x000000000000662c)
└ @ Atom C:\Users\VoSiLk\.julia\packages\Atom\ambhH\src\goto.jl:285
┌ Info: Symbols: UUIDs (26 / 63)
└   progress = 0.4126984126984127
┌ Info: Symbols: Juno (27 / 63)
└   progress = 0.42857142857142855
┌ Info: Symbols: Mmap (28 / 63)
└   progress = 0.4444444444444444
┌ Info: Symbols: TreeViews (29 / 63)
└   progress = 0.4603174603174603
┌ Info: Symbols: Core (30 / 63)
└   progress = 0.47619047619047616
┌ Info: Symbols: DataStructures (31 / 63)
└   progress = 0.49206349206349204
┌ Info: Symbols: SharedArrays (32 / 63)
└   progress = 0.5079365079365079
┌ Info: Symbols: InteractiveUtils (33 / 63)
└   progress = 0.5238095238095238
┌ Info: Symbols: Test (34 / 63)
└   progress = 0.5396825396825397
┌ Info: Symbols: Cassette (35 / 63)
└   progress = 0.5555555555555556
┌ Info: Symbols: SuiteSparse (36 / 63)
└   progress = 0.5714285714285714
┌ Info: Symbols: Requires (37 / 63)
└   progress = 0.5873015873015873
┌ Info: Symbols: SparseArrays (38 / 63)
└   progress = 0.6031746031746031
┌ Info: Symbols: LinearAlgebra (39 / 63)
└   progress = 0.6190476190476191
┌ Info: Symbols: OrderedCollections (40 / 63)
└   progress = 0.6349206349206349
┌ Info: Symbols: Markdown (41 / 63)
└   progress = 0.6507936507936508
┌ Info: Symbols: MacroTools (42 / 63)
└   progress = 0.6666666666666666
┌ Info: Symbols: Tokenize (43 / 63)
└   progress = 0.6825396825396826
┌ Info: Symbols: Sockets (44 / 63)
└   progress = 0.6984126984126984
┌ Info: Symbols: Printf (45 / 63)
└   progress = 0.7142857142857143
┌ Info: Symbols: JSON (46 / 63)
└   progress = 0.7301587301587301
┌ Info: Symbols: Logging (47 / 63)
└   progress = 0.746031746031746
┌ Info: Symbols: REPL (48 / 63)
└   progress = 0.7619047619047619
┌ Info: Symbols: SHA (49 / 63)
└   progress = 0.7777777777777778
┌ Info: Symbols: FileWatching (50 / 63)
└   progress = 0.7936507936507936
┌ Info: Symbols: Statistics (51 / 63)
└   progress = 0.8095238095238095
┌ Info: Symbols: Pkg (52 / 63)
└   progress = 0.8253968253968254
┌ Info: Symbols: Unicode (53 / 63)
└   progress = 0.8412698412698413
┌ Info: Symbols: Main (54 / 63)
└   progress = 0.8571428571428571
┌ Info: Symbols: DocSeeker (55 / 63)
└   progress = 0.873015873015873
┌ Info: Symbols: Base64 (56 / 63)
└   progress = 0.8888888888888888
┌ Info: Symbols: JuliaInterpreter (57 / 63)
└   progress = 0.9047619047619048
┌ Info: Symbols: Traceur (58 / 63)
└   progress = 0.9206349206349206
┌ Info: Symbols: Distributed (59 / 63)
└   progress = 0.9365079365079365
┌ Info: Symbols: HTTP (60 / 63)
└   progress = 0.9523809523809523
┌ Error: MethodError(Tokenize.Tokens.RawToken, (Tokenize.Tokens.EQEQ, (7, 12), (7, 14), 118, 119, Tokenize.Tokens.NO_ERR, false), 0x000000000000662c)
└ @ Atom C:\Users\VoSiLk\.julia\packages\Atom\ambhH\src\goto.jl:299
┌ Info: Symbols: Example (61 / 63)
└   progress = 0.9682539682539683
┌ Info: Symbols: WebSockets (62 / 63)
└   progress = 0.9841269841269841
┌ Info: Symbols: WebIO (63 / 63)
└   progress = 1.0
┌ Info: Finish symbols cache generation
└   progress = 1
Test Summary: | Pass  Total
goto symbols  |   54     54
Test Summary: | Pass  Total
datatip       |   17     17
Test Summary: | Pass  Total
workspace     |   20     20
Test Summary: | Pass  Total
Display       |    8      8
   Testing Atom tests passed

**Comment by VoSiLk** [comment]
Do you have now an idea what reasons the problem?

**Comment by VoSiLk** [comment]
For all who have the same problem. My current workaround is to use the versions (versions, which ares by JuliaPro 1.2.0-1):

Julia packages:
Atom v0.9.1
Juno v0.7.1
Note: to install a specific version of julia package enter the package manager within the Julia REPL via ```] ``` and then use i.e  ```add Juno@0.7.1 ``` command

Atom packages:
ink 0.10.12
julia-client 0.9.4
language-julia 0.19.1
Note: to install a specific version of atom package open a power shell window and then use i.e  
```apm install ink@0.10.12``` command

**Comment by pfitzseb** [comment]
Apparently something goes wrong when installing newer julia-client versions, which then subtly breaks some functionality. If you find the time, check whether you're seeing any errors in the Atom developer console (opened with <kbd>Ctrl-Shift-I</kbd>) after starting a Julia process (with a recent version of julia-client, of course).

**Comment by VoSiLk** [comment]
I assume that this specific problem is caused by change in the Juno package, because I faced another problem (the Julia REPL inside of Atom exits directly after starting it) with package configuration above, so that I updated all packages to recent version except the Juno package. But sure I will investigate it also with the recent version of the Juno package.

**Comment by VoSiLk** [comment]
This shows the console after I stopped Juno because of the freezing problem:

Julia Boot: 0.36s
8
evaluation.coffee:54 Error: Something went wrong while evaluating.
(anonymous)	@	evaluation.coffee:54
_tickCallback	@	internal/process/next_tick.js:68
Promise.then (async)		
(anonymous)	@	evaluation.coffee:51
eval	@	evaluation.coffee:37
(anonymous)	@	commands.coffee:27
withInk	@	commands.coffee:148
subs.add.atom.commands.add.julia-client:run-and-move	@	commands.coffee:25
handleCommandEvent	@	<embedded>:11
KeymapManager.dispatchCommandEvent	@	<embedded>:11
KeymapManager.handleKeyboardEvent	@	<embedded>:11
handleDocumentKeyEvent	@	<embedded>:11
events.js:167 Uncaught Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111)
errnoException	@	internal/errors.js:313
onStreamRead	@	internal/stream_base_commons.js:111

**Comment by VoSiLk** [comment]
I now work on the latest versions of all packages except for the Atom package. I use currently the version 0.9.1. Maybe this hint will help you to find the bug.

**Comment by njspeer** [comment]
I believe I am having the same problem.  Everything works perfectly on my Mac.  I installed Julia + Atom on my work computer (running Windows 7.1) and Julia seems to work fine, but trying to execute a single line of code from atom (or trying to execute a file), results in the Julia REPLE freezing.  I've tried two versions of Julia: 1.4 and 1.3.1.  I get the same result.

**Comment by pfitzseb** [comment]
Can you check [this](https://github.com/JunoLab/Juno.jl/issues/532#issuecomment-604926962) issue? It's likely the issue is Revise-related.

**Comment by njspeer** [comment]
Thanks for the rapid response.  I don't think so.  I checked, and I do not have a startup.jl file in either of my Julia directories.  Is there something else I should check?

**Comment by njspeer** [comment]
I uninstalled Atom and all packages and reinstalled it hoping that would solve the issue.  I installed only the package 'julia-client 0.12.4', which installed two dependencies:  'ink 0.12.3' and 'language-julia 0.19.3.'  I'm still having the same error.  I can start Julia in the REPL and execute commands (from within Atom), but as soon as I put a .jl file in focus, the Julia instance freezes, and  I can no longer execute code at that point, and no amount of time seems to help.  I eventually have to quit Atom and restart it.

**Comment by pfitzseb** [comment]
Does that happen for any file you open (even for a new file)? Did you make sure your Julia packages are up-to-date  (you should be on Atom.jl@0.12.10).

**Comment by njspeer** [comment]
I verified, through the Pkg API, that I have Atom v0.12.10.  I did this through the Atom REPL window.  I then typed a few simple commands into the REPL (2+2, 3+3, etc), all of which worked.  I then loaded a blank .jl file and my REPL Julia instance froze.

**Comment by aviatesk** [comment]
> loaded a blank .jl file

does this mean literally loading a file, i.e. run `include("hoge.jl")` where `hoge.jl` only has
an empty line ?

**Comment by njspeer** [comment]
Yes.  I made a file called 'helloworld.jl' that only had 'println('hello, world!'),' and the REPL froze as soon as I clicked on the file tab.  I then created a new empty file (name = 'untitled').  Putting this file into focus did nothing (REPL still worked fine).  Then I saved it as 'helloworld.jl,' overwriting the previous file, and as soon as I did that the REPL froze.

I also deleted every copy of Julia and Atom on my computer (including all Atom package files) and reinstalled Atom and Julia, then add only Juno, which installed about 8 different packages.  I then removed packages one by one until I only had the following three packages installed: 'julia-client 0.12.4', 'ink 0.12.3', and 'language-julia 0.19.3.'  Any fewer, and I could not run Julia.  With each package I removed, I check to see if the error was still present (it was).  As I mentioned, if I remove any of the remaining three packages, I no longer have Julia functionality in Atom.  So, I'm pretty sure the error is caused by one of those three packages.  I think that one of the packages is trying to read the Julia file when it comes into focus and is having some kind of error that is causing it to freeze.  I also left it in this frozen state for ~ 1 hour.  It never recovered (i.e., I eliminated the possibility that it was performing some process that was simply taking a long time).

This is an installation on my work computer, which is an i7 from about 2012, running Windows 7.1.  On my MacBook Pro (running OS X) everything works perfectly.  Furthermore, I have Windows 10 running on Parallels on my MacBook Pro;  when I install the same configuration on the MBP/Parallels/Win 10 environment, it works perfectly.

**Comment by aviatesk** [comment]
>  I also deleted every copy of Julia and Atom on my computer (including all Atom package files) and reinstalled Atom and Julia, then add only Juno, which installed about 8 different packages

Thanks for your try to debug. Well, we kinda know what _might_ be happening, and I guess repeating uninstall/installing each package is not so fun :P

Instead of that, can you share us with [the debug info](http://docs.junolab.org/stable/man/faq/#I-am-having-issues,-where-do-I-leave-a-bug-report?-1) ?

**Comment by mateuszatki** [comment]
I am struggling with the similar issue. Sometimes when I focus on the REPL its not responsive. The code in the editor window runs just fine, except that bottom console REPL is totally frozen. I can't restart it without closing and starting again Atom, which is very annoying. Happened yesterday couple of times.

I am using GNU/Linux Debian and atom 1.50 while Julia packages are Juno v0.8.3 and  Atom v0.12.19.

**Comment by pfitzseb** [comment]
You might be running into https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal?

**Comment by mateuszatki** [comment]
> You might be running into https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal?

Maybe! But it's super strange, cause Ctrl+s normally triggers search right? Furthermore, ctrl+c should revert it (it does work with Python's repl), but in Juno only Ctrl+q unblocks it and Ctrl+c does nothing.

**Comment by pfitzseb** [comment]
Well, that is a *terminal* feature, not a REPL or shell feature. You can however add `Ctrl-S` to the whitelisted keybindings (in the julia-client settings).
