### ISSUE TITLE
Julia exited with Error: Cannot find module '..\build\Debug\pty.node'.

### ISSUE THREAD

**Issue by johncwok** [JunoLab/Juno.jl#408]
As of today I cannot start a julia session with atom anymore, it exits immediately.
Upon opening the dev mode i have seen this notification :

```
Julia exited with Error: Cannot find module '..\build\Debug\pty.node'.
(anonymous) @ local.coffee:115
Promise.catch (async)
start @ local.coffee:108
_boot @ connection.coffee:42
boot @ connection.coffee:56
(anonymous) @ connection.coffee:18
terminal.startRequested @ console2.js:61
InkTerminal.enterhandler @ console.js:110
(anonymous) @ console.js:157
Terminal._keyDown @ C:\Users\cnelias\.atom\packages\ink\node_modules\xterm\lib\Terminal.js:1135
(anonymous) @ C:\Users\cnelias\.atom\packages\ink\node_modules\xterm\lib\Terminal.js:471
internal/modules/cjs/loader.js:584 Uncaught (in promise) Error: Cannot find module '..\build\Debug\pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/cnelias/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.loadNative (C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\utils.js:22:16)
    at new WindowsPtyAgent (C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\windowsPtyAgent.js:39:40)
    at new WindowsTerminal (C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\index.js:29:12)
    at file:///C:/Users/cnelias/.atom/packages/julia-client/lib/connection/process/basic2.js:93:26
Module._resolveFilename @ internal/modules/cjs/loader.js:584
Module._resolveFilename @ C:\Users\cnelias\AppData\Local\atom\app-1.41.0\resources\electron.asar\common\reset-search-paths.js:43
get_Module._resolveFilename @ <embedded>:11
Module.require @ index.js:61
require @ <embedded>:11
loadNative @ C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\utils.js:22
WindowsPtyAgent @ C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\windowsPtyAgent.js:39
WindowsTerminal @ C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\windowsTerminal.js:49
spawn @ C:\Users\cnelias\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\index.js:29
(anonymous) @ basic2.js:93
Promise.then (async)
_boot @ connection.coffee:45
boot @ connection.coffee:56
(anonymous) @ connection.coffee:18
terminal.startRequested @ console2.js:61
InkTerminal.enterhandler @ console.js:110
(anonymous) @ console.js:157
Terminal._keyDown @ C:\Users\cnelias\.atom\packages\ink\node_modules\xterm\lib\Terminal.js:1135
(anonymous) @ C:\Users\cnelias\.atom\packages\ink\node_modules\xterm\lib\Terminal.js:471
```
Anyone knows what is going on ? Yesterday everything was fine ..

**Comment by aviatesk** [comment]
close as dup of #410 and https://github.com/JunoLab/atom-julia-client/issues/642
