### ISSUE TITLE
[BUG] Julia exits right away.

### ISSUE THREAD

**Issue by xanfus** [JunoLab/Juno.jl#410]
# Details
- Atom version: 1.41.0
- Julia version: 1.3.0-rc4.1
- OS: Windows 10 1903 build 18362.418
- Package versions:
  - Atom.jl: 0.11.2
  - julia-client: 0.11.2
  - ink: 0.11.5

I've just updated Atom 1.40.1 -> 1.41.0. Julia:
```
Press Enter to start Julia. 

Julia has exited.
Press Enter to start a new session.

Julia has exited.
Press Enter to start a new session.
```

**Comment by xanfus** [comment]
Back on 1.40.1 with Atom.jl 0.11.2. Compiling...Success.

**Comment by aviatesk** [comment]
You may wan to watch on https://github.com/JunoLab/atom-julia-client/issues/642

**Comment by johncwok** [comment]
I have the same issue.

**Comment by pfitzseb** [comment]
Did you try un- and reinstalling julia-client?

**Comment by xanfus** [comment]
> Did you try un- and reinstalling julia-client?

I'll try that.

**Comment by johncwok** [comment]
It fixed the issue for me, thanks !

**Comment by xanfus** [comment]
> > Did you try un- and reinstalling julia-client?
> 
> I'll try that.

I've deleted .atom folder and reinstalled "uber-juno". Works nominally.

**Comment by braamvandyk** [comment]
Windows 10. Atom updated to 1.41.0 and this problem started. Uninstalled julia-client, after which it refuses to reinstall. Log file extract below. I wiped Atom completely and started from a clean install - julia-client refuses to install, even from the command prompt, with admin rights and McAfee disabled completely. Also tried this from Anaconda terminal, as the error displayed stated that the Python executable could not be found. It is in the path and the PYTHON environment variable is set. Typing `python` at the same prompt as I'm running `apm` from found Python just fine (Anaconda3 - Python 3.7).

I copied the julia-client package from another machine and could get Julia running in an external console only.

Then the other machine updated Atom (automatic updates - I must remember to switch that off!) and the exact same problem started. Uninstalling the client led to the same problem - it refuses to reinstall with the same errors. This machine does not run McAfee, so that is probably not the issue.

```
2435 verbose lifecycle @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3~install: CWD: C:\Users\vdykb\AppData\Local\Temp\apm-install-dir-119927-45072-rulg6d.t66s\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
2436 silly lifecycle @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3~install: Args: [ '/d /s /c', 'prebuild-install || node scripts/install.js' ]
2437 silly lifecycle @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3~install: Returned: code: 1  signal: null
2438 info lifecycle @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3~install: Failed to exec install script
2439 timing action:install Completed in 8322ms
2440 verbose unlock done using C:\Users\vdykb\.atom\.apm\_locks\staging-334847f4048a279e.lock for C:\Users\vdykb\AppData\Local\Temp\apm-install-dir-119927-45072-rulg6d.t66s\node_modules\.staging
2441 timing stage:rollbackFailedOptional Completed in 2274ms
2442 timing stage:runTopLevelLifecycles Completed in 43517ms
2443 silly saveTree apm-install-dir-119927-45072-rulg6d.t66s
2443 silly saveTree `-- julia-client@0.11.2
2443 silly saveTree   +-- @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3
2443 silly saveTree   | +-- nan@2.14.0
2443 silly saveTree   | `-- prebuild-install@5.3.0
2443 silly saveTree   |   +-- detect-libc@1.0.3
2443 silly saveTree   |   +-- expand-template@2.0.3
2443 silly saveTree   |   +-- github-from-package@0.0.0
2443 silly saveTree   |   +-- minimist@1.2.0
2443 silly saveTree   |   +-- mkdirp@0.5.1
2443 silly saveTree   |   | `-- minimist@0.0.8
2443 silly saveTree   |   +-- napi-build-utils@1.0.1
2443 silly saveTree   |   +-- node-abi@2.12.0
2443 silly saveTree   |   | `-- semver@5.7.1
2443 silly saveTree   |   +-- noop-logger@0.1.1
2443 silly saveTree   |   +-- npmlog@4.1.2
2443 silly saveTree   |   | +-- are-we-there-yet@1.1.5
2443 silly saveTree   |   | | +-- delegates@1.0.0
2443 silly saveTree   |   | | `-- readable-stream@2.3.6
2443 silly saveTree   |   | |   +-- core-util-is@1.0.2
2443 silly saveTree   |   | |   +-- inherits@2.0.4
2443 silly saveTree   |   | |   +-- isarray@1.0.0
2443 silly saveTree   |   | |   +-- process-nextick-args@2.0.1
2443 silly saveTree   |   | |   +-- safe-buffer@5.1.2
2443 silly saveTree   |   | |   +-- string_decoder@1.1.1
2443 silly saveTree   |   | |   `-- util-deprecate@1.0.2
2443 silly saveTree   |   | +-- console-control-strings@1.1.0
2443 silly saveTree   |   | +-- gauge@2.7.4
2443 silly saveTree   |   | | +-- aproba@1.2.0
2443 silly saveTree   |   | | +-- has-unicode@2.0.1
2443 silly saveTree   |   | | +-- object-assign@4.1.1
2443 silly saveTree   |   | | +-- signal-exit@3.0.2
2443 silly saveTree   |   | | +-- string-width@1.0.2
2443 silly saveTree   |   | | | +-- code-point-at@1.1.0
2443 silly saveTree   |   | | | +-- is-fullwidth-code-point@1.0.0
2443 silly saveTree   |   | | | | `-- number-is-nan@1.0.1
2443 silly saveTree   |   | | | `-- strip-ansi@3.0.1
2443 silly saveTree   |   | | |   `-- ansi-regex@2.1.1
2443 silly saveTree   |   | | +-- strip-ansi@3.0.1
2443 silly saveTree   |   | | `-- wide-align@1.1.3
2443 silly saveTree   |   | `-- set-blocking@2.0.0
2443 silly saveTree   |   +-- os-homedir@1.0.2
2443 silly saveTree   |   +-- pump@2.0.1
2443 silly saveTree   |   | +-- end-of-stream@1.4.4
2443 silly saveTree   |   | | `-- once@1.4.0
2443 silly saveTree   |   | |   `-- wrappy@1.0.2
2443 silly saveTree   |   | `-- once@1.4.0
2443 silly saveTree   |   +-- rc@1.2.8
2443 silly saveTree   |   | +-- deep-extend@0.6.0
2443 silly saveTree   |   | +-- ini@1.3.5
2443 silly saveTree   |   | `-- strip-json-comments@2.0.1
2443 silly saveTree   |   +-- simple-get@2.8.1
2443 silly saveTree   |   | +-- decompress-response@3.3.0
2443 silly saveTree   |   | | `-- mimic-response@1.0.1
2443 silly saveTree   |   | `-- simple-concat@1.0.0
2443 silly saveTree   |   +-- tar-fs@1.16.3
2443 silly saveTree   |   | +-- chownr@1.1.3
2443 silly saveTree   |   | +-- pump@1.0.3
2443 silly saveTree   |   | `-- tar-stream@1.6.2
2443 silly saveTree   |   |   +-- bl@1.2.2
2443 silly saveTree   |   |   +-- buffer-alloc@1.2.0
2443 silly saveTree   |   |   | +-- buffer-alloc-unsafe@1.1.0
2443 silly saveTree   |   |   | `-- buffer-fill@1.0.0
2443 silly saveTree   |   |   +-- fs-constants@1.0.0
2443 silly saveTree   |   |   +-- to-buffer@1.1.1
2443 silly saveTree   |   |   `-- xtend@4.0.2
2443 silly saveTree   |   +-- tunnel-agent@0.6.0
2443 silly saveTree   |   `-- which-pm-runs@1.0.0
2443 silly saveTree   +-- atom-package-deps@5.1.0
2443 silly saveTree   | +-- sb-fs@4.0.0
2443 silly saveTree   | | `-- strip-bom-buf@1.0.0
2443 silly saveTree   | |   `-- is-utf8@0.2.1
2443 silly saveTree   | `-- semver@6.3.0
2443 silly saveTree   +-- atom-space-pen-views@2.2.0
2443 silly saveTree   | +-- fuzzaldrin@2.1.0
2443 silly saveTree   | `-- space-pen@5.1.2
2443 silly saveTree   |   +-- grim@1.5.0
2443 silly saveTree   |   | `-- emissary@1.3.3
2443 silly saveTree   |   |   +-- es6-weak-map@0.1.4
2443 silly saveTree   |   |   | +-- d@0.1.1
2443 silly saveTree   |   |   | | `-- es5-ext@0.10.51
2443 silly saveTree   |   |   | |   +-- es6-iterator@2.0.3
2443 silly saveTree   |   |   | |   | +-- d@1.0.1
2443 silly saveTree   |   |   | |   | | `-- type@1.2.0
2443 silly saveTree   |   |   | |   | `-- es6-symbol@3.1.2
2443 silly saveTree   |   |   | |   +-- es6-symbol@3.1.2
2443 silly saveTree   |   |   | |   `-- next-tick@1.0.0
2443 silly saveTree   |   |   | +-- es5-ext@0.10.51
2443 silly saveTree   |   |   | +-- es6-iterator@0.1.3
2443 silly saveTree   |   |   | | `-- es6-symbol@2.0.1
2443 silly saveTree   |   |   | `-- es6-symbol@2.0.1
2443 silly saveTree   |   |   +-- mixto@1.0.0
2443 silly saveTree   |   |   +-- property-accessors@1.1.3
2443 silly saveTree   |   |   `-- underscore-plus@1.7.0
2443 silly saveTree   |   |     `-- underscore@1.9.1
2443 silly saveTree   |   +-- jquery@2.1.4
2443 silly saveTree   |   `-- underscore-plus@1.7.0
2443 silly saveTree   +-- etch@0.14.0
2443 silly saveTree   +-- fuzzaldrin-plus@0.6.0
2443 silly saveTree   +-- physical-cpu-count@2.0.0
2443 silly saveTree   +-- semver@6.3.0
2443 silly saveTree   +-- ssh2@0.8.5
2443 silly saveTree   | `-- ssh2-streams@0.4.6
2443 silly saveTree   |   +-- asn1@0.2.4
2443 silly saveTree   |   | `-- safer-buffer@2.1.2
2443 silly saveTree   |   +-- bcrypt-pbkdf@1.0.2
2443 silly saveTree   |   | `-- tweetnacl@0.14.5
2443 silly saveTree   |   `-- streamsearch@0.1.2
2443 silly saveTree   `-- underscore-plus@1.7.0
2444 warn enoent ENOENT: no such file or directory, open 'C:\Users\vdykb\AppData\Local\Temp\apm-install-dir-119927-45072-rulg6d.t66s\package.json'
2445 verbose enoent This is related to npm not being able to find a file.
2446 warn apm-install-dir-119927-45072-rulg6d.t66s No description
2447 warn apm-install-dir-119927-45072-rulg6d.t66s No repository field.
2448 warn apm-install-dir-119927-45072-rulg6d.t66s No README data
2449 warn apm-install-dir-119927-45072-rulg6d.t66s No license field.
2450 verbose stack Error: @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
2450 verbose stack Exit status 1
2450 verbose stack     at EventEmitter.<anonymous> (c:\Users\vdykb\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
2450 verbose stack     at EventEmitter.emit (events.js:182:13)
2450 verbose stack     at ChildProcess.<anonymous> (c:\Users\vdykb\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2450 verbose stack     at ChildProcess.emit (events.js:182:13)
2450 verbose stack     at maybeClose (internal/child_process.js:961:16)
2450 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
2451 verbose pkgid @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3
2452 verbose cwd C:\Users\vdykb\AppData\Local\Temp\apm-install-dir-119927-45072-rulg6d.t66s
2453 verbose Windows_NT 10.0.16299
2454 verbose argv "c:\\Users\\vdykb\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\bin\\node.exe" "c:\\Users\\vdykb\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\vdykb\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\vdykb\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/julia-client/versions/0.11.2/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
2455 verbose node v10.2.1
2456 verbose npm  v6.2.0
2457 error code ELIFECYCLE
2458 error errno 1
2459 error @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
2459 error Exit status 1
2460 error Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
2460 error This is probably not a problem with npm. There is likely additional logging output above.
2461 verbose exit [ 1, true ]
```

**Comment by pfitzseb** [comment]
Ok, I have no idea what's going on there. 
If you're willing to help debug this further: Can you try the [dev install instructions](http://docs.junolab.org/latest/devdocs/dev_install/#Atom-Packages-1) and report back?

**Comment by braamvandyk** [comment]
Happy to. I'll wipe Atom on my home PC and start with a fresh install of 1.41.0. Will report back ASAP.

**Comment by braamvandyk** [comment]
Clean Atom 1.41.0 install - I uninstalled and wiped the folders, including the packages.
Ran the dev installs from a Git bash and they all went without a hitch:

```
braam@Braam-PC2 MINGW64 ~
$ apm dev julia-client
Cloning https://github.com/JunoLab/atom-julia-client done
Installing modules done
C:\Users\braam\.atom\dev\packages\julia-client -> C:\Users\braam\github\julia-client

braam@Braam-PC2 MINGW64 ~
$ apm dev ink
Cloning https://github.com/JunoLab/atom-ink done
Installing modules done
C:\Users\braam\.atom\dev\packages\ink -> C:\Users\braam\github\ink

braam@Braam-PC2 MINGW64 ~
$ apm dev language-julia
Cloning https://github.com/JuliaEditorSupport/atom-language-julia done
Installing modules done
C:\Users\braam\.atom\dev\packages\language-julia -> C:\Users\braam\github\language-julia

braam@Braam-PC2 MINGW64 ~
$ apm dev latex-completions
Cloning https://github.com/JunoLab/atom-latex-completions done
Installing modules done
C:\Users\braam\.atom\dev\packages\latex-completions -> C:\Users\braam\github\latex-completions
```
Ran Atom in dev mode and Julia prompt started up smoothly. All good!

Is there a log file or similar somewhere that I can post? If needed, I'll wipe Atom again and repeat the exercise.
