### ISSUE TITLE
Press Enter to start Julia.   Julia has exited. Press Enter to start a new session.[BUG]

### ISSUE THREAD

**Issue by VivMendes376** [JunoLab/Juno.jl#412]
Yesterday Atom and Julia were working OK in my computer at home (windows 10). Atom and Julia  worked OK during all day in my office (windows 10). I arrived home, started my computer, launched Atom, it asked me straight away to update some packages (Hydrogen, I think) and to confirm whether I wanted Atom to become the default atom:// URI handler automatically (to which I replied "Yes"), please restart Atom and ... bhum:

**"Press Enter to start Julia.  Julia has exited."** , **"Press Enter to start Julia.  Julia has exited."**  ...

I simply do not undesrtand what's going on, because I did not do anything else than answering to the demands of Atom.

Help would be extremelly appreciated as I am in the middle of a course on computational economics, using Julia, and with these recorrent problems with Atom is not easy to convince students to move away from Matlab.

**Comment by VivMendes376** [comment]
Now I'm getting this Error:

C:\Users\Utilizador\.atom\packages\ink\lib\console\console.js:246
Hide Stack Trace
Error: Need to attach a pty before pasting.
    at InkTerminal.paste (file:///C:/Users/Utilizador/.atom/packages/ink/lib/console/console.js:246:13)
    at HTMLElement.inkTerminalPaste (file:///C:/Users/Utilizador/.atom/packages/ink/lib/console/console.js:35:16)
    at CommandRegistry.handleCommandEvent (C:\Users\Utilizador\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (C:\Users\Utilizador\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (C:\Users\Utilizador\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\Utilizador\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:284598)

**Comment by VivMendes376** [comment]
Solved the problem. Uninstalled Julia-Client and re-installed it again. Many new icons in the Toggle toolbar.

**Comment by eliassarr** [comment]
I had the same issue so I installed some recommended updates and it was all fixed.
