### ISSUE TITLE
Julia REPL will not start in Atom

### ISSUE THREAD

**Issue by TomBuckleyLab** [JunoLab/Juno.jl#426]
I had Julia working fine in Juno/Atom for a few weeks (PC running Windows 10 Pro 64-bit, Atom 1.41.0, Julia 1.2.0). Then when I returned to work after the weekend, the REPL wouldn't start. It just says "Julia has exited" immediately after I press enter to start a new session in the REPL panel. Julia will start successfully from the command prompt. I uninstalled and reinstalled Julia to no effect. The debugger gives the errors listed below. Can anybody help?

Julia exited with Error: Cannot find module '..\build\Debug\pty.node'.
(anonymous) @ C:\Users\tomb\.atom\packages\julia-client\lib\connection\local.coffee:175

Uncaught (in promise) Error: Cannot find module '..\build\Debug\pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\tomb\AppData\Local\atom\app-1.41.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\tomb\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/tomb/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\tomb\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.loadNative (C:\Users\tomb\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\utils.js:22:16)
    at new WindowsPtyAgent (C:\Users\tomb\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\windowsPtyAgent.js:39:40)
    at new WindowsTerminal (C:\Users\tomb\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\tomb\.atom\packages\julia-client\node_modules\@pfitzseb\node-pty-prebuilt\lib\index.js:29:12)
    at file:///C:/Users/tomb/.atom/packages/julia-client/lib/connection/process/basic.js:105:26

**Comment by pfitzseb** [comment]
What most likely happened here is that Atom auto-updated to a new version, which unfortunately broke Juno. Reinstalling the julia-client package should fix this problem though.
If you have difficulties doing that from the Atom UI, try 
```
apm uninstall julia-client
apm install julia-client
```
in a terminal after closing all Atom instances.

**Comment by TomBuckleyLab** [comment]
That solved it! Thank you so much!
