### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rekabrnalla** [JunoLab/Juno.jl#438]
**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.9.4

### Stack Trace

Failed to activate the julia-client package

```
At Cannot find module '../build/Debug/pty.node'

Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.loadNative (/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/utils.js:22:16)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:24:19)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:255:3)
    at Module.get_Module._compile (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:14:20)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:52:3)
    at Module.get_Module._compile (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/julia-client/lib/connection/process/basic2.js:3:24)
    at /packages/julia-client/lib/connection/process/basic2.js:174:2)
    at Module.get_Module._compile (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/JuliaPro-1.2.0-1.app/Contents/MacOS/JuliaPro-Juno-1.2.0-1.app/Contents/Resources/JuliaPro-Juno-1.2.0-1/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
```

### Commands

```
     -3:31.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
default-language 0.3.1 
ink 0.10.12 
julia-client 0.9.4 
language-julia 0.19.1 
latex-completions 0.3.6 
project-manager 3.3.7 
tool-bar 1.1.12 
```

This happens on startup.  Not sure what happened to make it start doing this.  Sorry if this is a repeat.  I didn't see it.

**Comment by aviatesk** [comment]
Please kill the Atom process, update julia-client and ink package and then restart Atom.
