### ISSUE TITLE
julia-client install failed ENOENT: no such file or directory, open '...\apm-install-dir-120124-35008-40fjld.jxg3x\package.json'

### ISSUE THREAD

**Issue by zygmuntszpak** [JunoLab/Juno.jl#498]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.440
- Julia version: 1.3.1
- OS: Windows 10 64bit
- Package versions:
  - Atom.jl: 0.12.5
  - julia-client: 0.12.2
  - ink: 0.12.2

### Steps to reproduce
Uninstalled all Julia related packages from Atom.
Installed Julia version 1.3.1
Installed Atom and Juno packages
Then...

Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Spock>apm install ink
Installing ink to C:\Users\Spock\.atom\packages done

C:\Users\Spock>apm install language-julia
Installing language-julia to C:\Users\Spock\.atom\packages done

C:\Users\Spock>apm install julia-client
Installing julia-client to C:\Users\Spock\.atom\packages failed

> node-pty-prebuilt-multiarch@0.9.0 install C:\Users\Spock\AppData\Local\Temp\apm-install-dir-120124-35008-40fjld.jxg3x\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\Spock\AppData\Local\Temp\apm-install-dir-120124-35008-40fjld.jxg3x\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\Spock\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Spock\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

prebuild-install WARN install unexpected end of file
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Spock\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Spock\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Spock\AppData\Local\atom\app-1.44.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Spock\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Spock\\AppData\\Local\\atom\\app-1.44.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Spock\AppData\Local\Temp\apm-install-dir-120124-35008-40fjld.jxg3x\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Spock\AppData\Local\Temp\apm-install-dir-120124-35008-40fjld.jxg3x\package.json'
npm WARN apm-install-dir-120124-35008-40fjld.jxg3x No description
npm WARN apm-install-dir-120124-35008-40fjld.jxg3x No repository field.
npm WARN apm-install-dir-120124-35008-40fjld.jxg3x No README data
npm WARN apm-install-dir-120124-35008-40fjld.jxg3x No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Spock\.atom\.apm\_logs\2020-02-24T06_59_07_437Z-debug.log

I've attached the complete log file. 

[log.txt](https://github.com/JunoLab/Juno.jl/files/4243392/log.txt)

**Comment by pfitzseb** [comment]
Hm, `prebuild-install WARN install unexpected end of file` sounds like you got a corrupted file (or your antivirus software tried to delete it). Does this happen every time you try installing julia-client?

**Comment by zygmuntszpak** [comment]
This is happening every time I try to install julia-client. I didn't encounter this issue with previous versions of julia-client on the same machine. I'm not running any particular anti-virus software such as Norton, Symantec etc. 

```julia
 Can't find Python executable "python", you can set the PYTHON env variable
```

Should I be defining the PYTHON env variable?

**Comment by pfitzseb** [comment]
The current setup tries to download prebuilt binaries from github, which -- for some reason -- fails for you. As a fallback we try building the binary on your machine, which is kinda fiddly to set up.

So yes, you can try to point `PYTHON` to a Python 2 instance after following the [installation instructions for node-pty](https://github.com/microsoft/node-pty#windows).

**Comment by zygmuntszpak** [comment]
Thanks, I will give it a go tomorrow once I am back at that particular machine.

**Comment by zygmuntszpak** [comment]
Unfortunately, all my attempts at getting this to work so far have failed. It seems that a TEMP directory containing the julia-client scripts etc. gets deleted before its install scripts are executed. 

`2391 verbose lifecycle node-pty-prebuilt-multiarch@0.9.0~install: CWD: C:\Users\Spock\AppData\Local\Temp\apm-install-dir-120128-2504-l39f64.esq4b\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
2392 silly lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Args: [ '/d /s /c', 'prebuild-install || node scripts/install.js' ]
2393 silly lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Returned: code: 1  signal: null
2394 info lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Failed to exec install script`

I tried to set everything up to build but it is failing with error messages that I can't make sense of. 

I ran `apm install julia-client --verbose` and got pages of error messages for `winpty.vcproj` that complain about unexpected tokens etc. as if an incorrect compiler is being used. It says things such as `This version of node/NAN/v8 requires a C++11 compiler`. 

I've attached the verbose output, as well as the concomitant log file.
[verbose_error.txt](https://github.com/JunoLab/Juno.jl/files/4265232/verbose_error.txt)
[log.txt](https://github.com/JunoLab/Juno.jl/files/4265234/log.txt)

Thanks for any help you might be able to offer.

**Comment by zygmuntszpak** [comment]
I think that this may be an issue with `Atom 1.44.0`. I deleted all my atom folders, including 

- C:\Users\<user name>\.atom 
- C:\Users\<user name>\AppData\Local\atom 
- C:\Users\<user name>\AppData\Roaming\Atom 

I then downloaded the `atom-windows.zip` https://github.com/atom/atom/releases/tag/v1.42.0 (should have actually downloaded the x64 version instead) and extracted it. 

Upon launching that version of Atom, I installed `uber-juno` which installed the relevant packages without any problems. Because Atom is now a "local" install it seems like I no longer have `apm`.  

I will try a similar procedure with newer versions of a "local" Atom installation next week. Maybe something got messed up with `apm` itself.

**Comment by pfitzseb** [comment]
Yes, it's likely that the global `apm` install got messed up somehow. Some people have reported that [apx](https://github.com/Aerijo/apx) got around the installation issues, so you could give that a go as well.
