### ISSUE TITLE
Failed to activate Julia package after update

### ISSUE THREAD

**Issue by aquaresima** [JunoLab/Juno.jl#501]
Hi,
I am running OpenSuse 15.
My Julia-client version is 0.8.10. There are no available updates.

Today I updated the Julia package as suggested in Juno, after restart I get this error (see later).
As a consequence, the Julia console does not start. I am very very troubled by this ehehe!
Can I at least downgrade?

Best

`
**Uncaught TypeError: Cannot read property 'close' of undefined**
TypeError: Cannot read property 'close' of undefined
    at Object.close (/home/alequa/.atom/packages/julia-client/lib/runtime/console2.js:154:18)
    at /home/alequa/.atom/packages/julia-client/lib/ui/layout.js:40:19
    at Array.map (native)
    at closePromises (/home/alequa/.atom/packages/julia-client/lib/ui/layout.js:39:26)
    at Object.restoreDefaultLayout (/home/alequa/.atom/packages/julia-client/lib/ui/layout.js:101:15)
    at /home/alequa/.atom/packages/julia-client/lib/julia-client.coffee:28:37
`

and the relative fail in julia-client

`
TypeError: this.scopes.some is not a function
    at BreakpointManager.appliesToEditor (/home/alequa/.atom/packages/ink/lib/debugger/breakpoints.js:102:24)
    at /home/alequa/.atom/packages/ink/lib/debugger/breakpoints.js:77:20
    at TextEditor.observeGrammar (/usr/share/atom/resources/app/src/text-editor.js:752:11)
    at /home/alequa/.atom/packages/ink/lib/debugger/breakpoints.js:76:26
    at Workspace.observeActiveTextEditor (/usr/share/atom/resources/app/src/workspace.js:724:11)
    at new BreakpointManager (/home/alequa/.atom/packages/ink/lib/debugger/breakpoints.js:74:34)
    at Object.activate (/home/alequa/.atom/packages/julia-client/lib/runtime/debugger.js:30:17)
    at Object.consumeInk (/home/alequa/.atom/packages/julia-client/lib/runtime.coffee:28:15)
    at Object.consumeInk (/home/alequa/.atom/packages/julia-client/lib/julia-client.coffee:48:7)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (/usr/share/atom/resources/app/src/package.js:405:79)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:233:20)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/usr/share/atom/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
`

**Comment by aquaresima** [comment]
The issue solved itself after a few restarts. 

The rubber duck effect is always lurking. 
Bytheway, maybe the report can be useful for debugging

**Comment by aviatesk** [comment]
I'm half sure you didn't restart Atom process when you faced the issue, did you ?

**Comment by aquaresima** [comment]
Then you are half wrong. 
I restarted Atom and even the computer.

After tinkering with it a bit I managed to start the Julia console. However, the code cannot be run 'line by line' as I used to do.  Not even 'by block' or 'by file' using the lateral bar

**Comment by aviatesk** [comment]
don't know but there's no file named `console2.js` in the latest versions of atom-julia-client anymore, so the error
shouldn't happen after clean update.
Making sure restart all the Atom process after update will solve probs you faced.

**Comment by aquaresima** [comment]
Do you know of any temporary folder that could be storing these files?
I closed the editor and tried 'pkill atom'. 
Now the error does not occur anymore.

Anyway, I can't run the code by the file. 
If I try the console gets stuck. With Ctrl-C I get
`ERROR: InterruptException:
Stacktrace:
 [1] poptaskref(::Base.InvasiveLinkedListSynchronized{Task}) at ./task.jl:660
 [2] wait() at ./task.jl:667
 [3] wait(::Base.GenericCondition{Base.Threads.SpinLock}) at ./condition.jl:106
 [4] lock(::ReentrantLock) at ./lock.jl:80
 [5] evalrepl(::Module, ::String) at /usr/local/share/julia/home/packages/Atom/N5oSJ/src/repl.jl:201
 [6] top-level scope at /usr/local/share/julia/home/packages/Atom/N5oSJ/src/repl.jl:252
 [7] eval(::Module, ::Any) at ./boot.jl:330
 [8] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:86
 [9] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:118 [inlined]
 [10] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:333
ERROR: unlock from wrong thread
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] unlock(::ReentrantLock) at ./lock.jl:101
 [3] evalrepl(::Module, ::String) at /usr/local/share/julia/home/packages/Atom/N5oSJ/src/repl.jl:231
 [4] top-level scope at /usr/local/share/julia/home/packages/Atom/N5oSJ/src/repl.jl:252`

Thanks for helping

**Comment by aviatesk** [comment]
Try update Atom.jl to the latest (0.12.7) 👍

**Comment by aquaresima** [comment]
(v1.3) pkg> status
    Status `/usr/local/share/julia/home/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.12.7

**Comment by aviatesk** [comment]
ah, please open an another issue on this with MRE, please.

**Comment by aquaresima** [comment]
Ok, thanks.

**Comment by pfitzseb** [comment]
What version of julia-client are you on after the update? You **need** 0.12.x for Atom.jl 0.12.x to work properly.

**Comment by aquaresima** [comment]
My Julia-client version is 0.8.10. There are no available updates.

**Comment by pfitzseb** [comment]
What version of Atom are you running?

**Comment by vlandau** [comment]
> If I try the console gets stuck. With Ctrl-C I get

I'm having this exact same issue, detailed on the Julia discourse [here](https://discourse.julialang.org/t/calling-a-function-breaks-repl-in-juno-error-unlock-from-wrong-thread/36165)
