### ISSUE TITLE
i just instaled uber-juno and already have a problem

### ISSUE THREAD

**Issue by vbifrhen** [JunoLab/Juno.jl#539]
I have a problem with
Uncaught (in promise) Error: Fetching outdated packages and themes failed.
    at C:\Users\User\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:938805
    at r (C:\Users\User\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:936821)
    at n (C:\Users\User\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14:1125047)
    at ChildProcess.o.process.on.e (C:\Users\User\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14:1125253)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

**Comment by pfitzseb** [comment]
Seems like you can't download packages from atom.io -- that's probably a problem with your internet connection or firewall. In any case, it doesn't seem to be related to Juno at all.
