### ISSUE TITLE
Uncaught TypeError: log is not a function 

### ISSUE THREAD

**Issue by birusod** [JunoLab/Juno.jl#614]
Steps:
df = DataFrame(x_float..y_string..z_string..)
plot(df, x = :x_float, y = :y_string, ygroup = :z_string, Geom.subplot_grid(Geom.boxplot))

Error:

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.12.6

### Stack Trace

Uncaught TypeError: log is not a function

```
At /Users/birusod/.atom/packages/julia-client/lib/runtime/plots.js:17

TypeError: log is not a function
    at consoleLog (/packages/julia-client/lib/runtime/plots.js:17:3)
    at /packages/julia-client/lib/runtime/plots.js:112:48)
    at WebViewImpl.dispatchEvent (/Applications/JuliaPro-1.4.1-1.app/Contents/MacOS/JuliaPro-Juno-1.4.1-1.app/Contents/Resources/JuliaPro-Juno-1.4.1-1/Contents/Resources/electron.asar/renderer/web-view/web-view-impl.js:100:26)
    at dispatchEvent (/Applications/JuliaPro-1.4.1-1.app/Contents/MacOS/JuliaPro-Juno-1.4.1-1.app/Contents/Resources/JuliaPro-Juno-1.4.1-1/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:52:13)
    at EventEmitter.<anonymous> (/Applications/JuliaPro-1.4.1-1.app/Contents/MacOS/JuliaPro-Juno-1.4.1-1.app/Contents/Resources/JuliaPro-Juno-1.4.1-1/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:68:9)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/Applications/JuliaPro-1.4.1-1.app/Contents/MacOS/JuliaPro-Juno-1.4.1-1.app/Contents/Resources/JuliaPro-Juno-1.4.1-1/Contents/Resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -6:02.9.0 editor:newline (input.hidden-input)
     -5:13.7.0 core:copy (input.hidden-input)
     -5:10.5.0 core:paste (input.hidden-input)
     -5:07.0 editor:newline (input.hidden-input)
 10x -5:04.8.0 core:backspace (input.hidden-input)
  6x -3:18.4.0 core:move-right (input.hidden-input)
     -3:16.9.0 core:backspace (input.hidden-input)
     -3:13 julia-client:run-and-move (input.hidden-input)
     -2:50.5.0 core:copy (input.hidden-input)
     -2:48 core:paste (input.hidden-input)
     -2:45.9.0 core:backspace (input.hidden-input)
     -2:37.6.0 core:cut (input.hidden-input)
     -2:34.3.0 core:paste (input.hidden-input)
  2x -2:24.2.0 julia-client:run-and-move (input.hidden-input)
     -1:11.1.0 core:backspace (input.hidden-input)
  3x -0:58 julia-client:run-and-move (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
hey-pane 1.2.0 
Hydrogen 2.14.6 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.5 
julia-client 0.12.6 
language-julia 0.19.3 
latex-completions 0.3.6 
monokai 0.24.0 
seti-ui 1.11.0 
tool-bar 1.4.1 
uber-juno 0.3.0 
```

**Comment by birusod** [comment]
Hope that helps fix the bug!
