### ISSUE TITLE
Juno: Error installing package julia-client

### ISSUE THREAD

**Issue by sivsoerensen** [JunoLab/Juno.jl#626]
Been trying to reinstall Julia all evening without luck. Tried reinstalled Atom as well. Error message:

Error: Installing “julia-client@0.12.6” failed.

"Please check your internet connection, or report this to https://github.com/JunoLab/Juno.jl/issues or https://discourse.julialang.org and we'll try to help." - hence here I am
<img width="474" alt="Screenshot 2021-02-10 at 23 55 32" src="https://user-images.githubusercontent.com/72440899/107583874-dfc31700-6bfb-11eb-9417-9e2988eff94c.png">

**Comment by pfitzseb** [comment]
Try `apm install julia-client` in a terminal, which should give a much more informative error message.

**Comment by mauriziodidomenico** [comment]
Hi, 
i have the same problem on a Windows 10 machine. 

find below the shell output:

shell> apm.cmd install julia-client
Installing julia-client to C:\Users\datdidomenm\.atom\packages failed

> node-pty-prebuilt-multiarch@0.9.0 install C:\Users\DATDID~1\AppData\Local\Temp\apm-install-dir-2021427-18524-6hqelo.75wx\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\DATDID~1\AppData\Local\Temp\apm-install-dir-2021427-18524-6hqelo.75wx\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\datdidomenm\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\datdidomenm\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

prebuild-install WARN install unable to get local issuer certificate
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\datdidomenm\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\datdidomenm\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\datdidomenm\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\datdidomenm\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\datdidomenm\\AppData\\Local\\atom\\app-1.57.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\datdidomenm\\AppData\\Local\\atom\\app-1.57.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\DATDID~1\AppData\Local\Temp\apm-install-dir-2021427-18524-6hqelo.75wx\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\DATDID~1\AppData\Local\Temp\apm-install-dir-2021427-18524-6hqelo.75wx\package.json'
npm WARN apm-install-dir-2021427-18524-6hqelo.75wx No description
npm WARN apm-install-dir-2021427-18524-6hqelo.75wx No repository field.
npm WARN apm-install-dir-2021427-18524-6hqelo.75wx No README data
npm WARN apm-install-dir-2021427-18524-6hqelo.75wx No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\datdidomenm\.atom\.apm\_logs\2021-05-27T07_20_34_922Z-debug.log


shell>

**Comment by superbigice** [comment]
I have the same problem。

**Comment by saeedehbasir** [comment]
I have the same problem
