### ISSUE TITLE
Windows 10 Cant start Julia process

### ISSUE THREAD

**Issue by jamblejoe** [JunoLab/Juno.jl#632]
On Windows 10 and julia-client 0.12.6 I can not start julia consoles anymore. The error in the console is 

```
innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js
- C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js
- C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection\process\basic.js
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection\process\cycler.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection\local.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\package\config.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\julia-client.coffee
- C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:157820)
    at Module.require (file:///C:/Users/gnakerst/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at new WindowsPtyAgent (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:39:40)
    at new WindowsTerminal (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28:12)
    at file:///C:/Users/gnakerst/.atom/packages/julia-client/lib/connection/process/basic.js:58:24
WindowsPtyAgent @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:42
WindowsTerminal @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49
spawn @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28
(anonymous) @ basic.js:58
Promise.then (async)
(anonymous) @ basic.js:56
Promise.then (async)
(anonymous) @ basic.js:55
Promise.then (async)
(anonymous) @ basic.js:54
getProcess @ basic.js:53
get_ @ basic.js:24
(anonymous) @ basic.js:13
(anonymous) @ misc.coffee:51
Promise.then (async)
(anonymous) @ misc.coffee:50
get @ basic.js:12
spawnJulia @ local.coffee:89
(anonymous) @ local.coffee:70
Promise.then (async)
start @ local.coffee:63
_boot @ connection.coffee:35
boot @ connection.coffee:51
(anonymous) @ connection.coffee:14
terminal.startRequested @ console.js:62
InkTerminal.enterhandler @ console.js:129
(anonymous) @ console.js:221
t._keyDown @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
(anonymous) @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
local.coffee:86 Julia exited with Error: The module '\\?\C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)..
(anonymous) @ local.coffee:85
Promise.catch (async)
start @ local.coffee:82
_boot @ connection.coffee:35
boot @ connection.coffee:51
(anonymous) @ connection.coffee:14
terminal.startRequested @ console.js:62
InkTerminal.enterhandler @ console.js:129
(anonymous) @ console.js:221
t._keyDown @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
(anonymous) @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
electron/js2c/asar.js:140 Uncaught (in promise) Error: The module '\\?\C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/gnakerst/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at new WindowsPtyAgent (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:35:36)
    at new WindowsTerminal (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28:12)
    at file:///C:/Users/gnakerst/.atom/packages/julia-client/lib/connection/process/basic.js:58:24
func @ electron/js2c/asar.js:140
Module._extensions..node @ internal/modules/cjs/loader.js:1034
func @ electron/js2c/asar.js:140
Module.load @ internal/modules/cjs/loader.js:815
Module._load @ internal/modules/cjs/loader.js:727
Module._load @ electron/js2c/asar.js:769
Module.require @ index.js:72
require @ <embedded>:11
WindowsPtyAgent @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:35
WindowsTerminal @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49
spawn @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28
(anonymous) @ basic.js:58
Promise.then (async)
_boot @ connection.coffee:40
boot @ connection.coffee:51
(anonymous) @ connection.coffee:14
terminal.startRequested @ console.js:62
InkTerminal.enterhandler @ console.js:129
(anonymous) @ console.js:221
t._keyDown @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
(anonymous) @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:42 innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js
- C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js
- C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection\process\basic.js
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection\process\cycler.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection\local.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\connection.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\package\config.coffee
- C:\Users\gnakerst\.atom\packages\julia-client\lib\julia-client.coffee
- C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:157820)
    at Module.require (file:///C:/Users/gnakerst/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at new WindowsPtyAgent (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:39:40)
    at new WindowsTerminal (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28:12)
    at file:///C:/Users/gnakerst/.atom/packages/julia-client/lib/connection/process/basic.js:58:24
WindowsPtyAgent @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:42
WindowsTerminal @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49
spawn @ C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28
(anonymous) @ basic.js:58
Promise.then (async)
(anonymous) @ basic.js:56
Promise.then (async)
(anonymous) @ basic.js:55
Promise.then (async)
(anonymous) @ basic.js:54
getProcess @ basic.js:53
get_ @ basic.js:24
(anonymous) @ basic.js:13
(anonymous) @ misc.coffee:51
Promise.then (async)
(anonymous) @ misc.coffee:50
get @ basic.js:12
spawnJulia @ local.coffee:89
(anonymous) @ local.coffee:70
Promise.then (async)
start @ local.coffee:63
_boot @ connection.coffee:35
boot @ connection.coffee:51
(anonymous) @ connection.coffee:14
terminal.startRequested @ console.js:62
InkTerminal.enterhandler @ console.js:129
(anonymous) @ console.js:221
t._keyUp @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
(anonymous) @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
local.coffee:86 Julia exited with Error: The module '\\?\C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)..
(anonymous) @ local.coffee:85
Promise.catch (async)
start @ local.coffee:82
_boot @ connection.coffee:35
boot @ connection.coffee:51
(anonymous) @ connection.coffee:14
terminal.startRequested @ console.js:62
InkTerminal.enterhandler @ console.js:129
(anonymous) @ console.js:221
t._keyUp @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
(anonymous) @ C:\Users\gnakerst\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1
electron/js2c/asar.js:140 Uncaught (in promise) Error: The module '\\?\C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/gnakerst/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at new WindowsPtyAgent (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:35:36)
    at new WindowsTerminal (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\gnakerst\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\lib\index.js:28:12)
    at file:///C:/Users/gnakerst/.atom/packages/julia-client/lib/connection/process/basic.js:58:24
```

**Comment by jamblejoe** [comment]
Uninstall - reinstall of the julia-client package resolved the issue

**Comment by pfitzseb** [comment]
Yeah, also see http://docs.junolab.org/latest/man/update/.
