### ISSUE TITLE
Juno: Error installing package julia-client [BUG]

### ISSUE THREAD

**Issue by tharannew** [JunoLab/Juno.jl#636]
![uber_juno_package](https://user-images.githubusercontent.com/86056254/122391224-5ce50b00-cfa5-11eb-9dc2-ffef7890cdd9.PNG)
 Been trying to download the uber-juno package on atom but this problem keeps popping up. Don't think it's and issue with my internet. Anything that can be done to overcome this?
 
 Thanks!

**Comment by P-J-Y** [comment]
I get the same issue! The error information is as follow: 

`> node-pty-prebuilt-multiarch@0.9.0 install C:\Users\jy\AppData\Local\Temp\apm-install-dir-2021830-17576-jfyuuj.2915n\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\jy\AppData\Local\Temp\apm-install-dir-2021830-17576-jfyuuj.2915n\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install unable to verify the first certificate
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\jy\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Users\\jy\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jy\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jy\AppData\Local\Temp\apm-install-dir-2021830-17576-jfyuuj.2915n\node_modules\julia-client\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jy\AppData\Local\Temp\apm-install-dir-2021830-17576-jfyuuj.2915n\package.json'
npm WARN apm-install-dir-2021830-17576-jfyuuj.2915n No description
npm WARN apm-install-dir-2021830-17576-jfyuuj.2915n No repository field.
npm WARN apm-install-dir-2021830-17576-jfyuuj.2915n No README data
npm WARN apm-install-dir-2021830-17576-jfyuuj.2915n No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jy\.atom\.apm\_logs\2021-09-30T05_03_14_279Z-debug.log`

**Comment by ylengwiler** [comment]
Error installing uber-juno

![image](https://user-images.githubusercontent.com/11032103/146603110-ea5d47c1-e4c5-4b33-9e4a-4d9e7ea8106d.png)

**Comment by brianbecsi** [comment]
[2022-05-29T00_31_00_091Z-debug.log](https://github.com/JunoLab/Juno.jl/files/8792507/2022-05-29T00_31_00_091Z-debug.log)

same issue here

**Comment by goyalyashpal** [comment]
yeah
