### ISSUE TITLE
Cant open files after installing Juno

### ISSUE THREAD

**Issue by KristofferC** [JunoLab/Juno.jl#99]
Same as https://discourse.julialang.org/t/ann-juno-0-6-7/8622/7?u=kristoffer.carlsson

Error message:

```
Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at /Users/kristoffer/.atom/packages/ink/lib/util/pane-item.js:56:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1197:26)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
```

**Comment by pfitzseb** [comment]
Thanks for the report and the error message :)
